#!/bin/bash
# Quick PostgreSQL Migration - Manual Steps

echo "=== Quick PostgreSQL Migration Guide ==="
echo ""
echo "STEP 1: Install PostgreSQL (if not installed)"
echo "----------------------------------------------"
echo "sudo apt update"
echo "sudo apt install postgresql postgresql-contrib"
echo ""

echo "STEP 2: Backup Your SQLite Data"
echo "----------------------------------------------"
echo "cp db.sqlite3 db.sqlite3.backup"
echo "source .venv/bin/activate"
echo "python manage.py dumpdata --exclude=contenttypes --exclude=auth.permission --indent=2 > sqlite_backup.json"
echo ""

echo "STEP 3: Create PostgreSQL Database"
echo "----------------------------------------------"
echo "sudo -u postgres psql"
echo "Then in PostgreSQL prompt:"
echo "  CREATE DATABASE news_db;"
echo "  CREATE USER news_user WITH PASSWORD 'your_password';"
echo "  GRANT ALL PRIVILEGES ON DATABASE news_db TO news_user;"
echo "  \\q"
echo ""

echo "STEP 4: Update gis/settings.py"
echo "----------------------------------------------"
echo "Change the DATABASES setting to:"
echo "  'ENGINE': 'django.db.backends.postgresql',"
echo "  'NAME': 'news_db',"
echo "  'USER': 'news_user',"
echo "  'PASSWORD': 'your_password',"
echo "  'HOST': 'localhost',"
echo "  'PORT': '5432',"
echo ""

echo "STEP 5: Run Migrations"
echo "----------------------------------------------"
echo "source .venv/bin/activate"
echo "python manage.py migrate"
echo ""

echo "STEP 6: Load Your Data"
echo "----------------------------------------------"
echo "python manage.py loaddata sqlite_backup.json"
echo ""

echo "STEP 7: Test"
echo "----------------------------------------------"
echo "python manage.py runserver"
echo "Visit: http://localhost:8000"
echo ""

echo "=== OR Use Automated Script ==="
echo "./migrate_postgres.sh"
echo ""
