# Generated by Django 5.2.8 on 2025-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('political', 'Political'), ('tech', 'Tech'), ('education', 'Education')], default='business', max_length=50),
        ),
    ]
