# Generated by Django 5.2.8 on 2025-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('tech_editor', 'Tech Editor'), ('political_analyst', 'Political Analyst'), ('business_reporter', 'Business Reporter'), ('sports_reporter', 'Sports Reporter'), ('senior_editor', 'Senior Editor'), ('staff_writer', 'Staff Writer'), ('photographer', 'Photographer'), ('video_journalist', 'Video Journalist')], max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Brief biography of the team member')),
                ('photo', models.ImageField(blank=True, help_text='Professional headshot', null=True, upload_to='team_photos/')),
                ('email', models.EmailField(blank=True, help_text='Professional email address', max_length=254)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('is_active', models.BooleanField(default=True, help_text='Is this team member currently active?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
