# Generated by Django 5.2.8 on 2025-11-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Select the author from team members', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.teammember'),
        ),
    ]
