# Generated by Django 5.2.8 on 2025-11-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("last_shared", models.DateTimeField(auto_now=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Count",
                "verbose_name_plural": "Share Counts",
                "unique_together": {("news", "platform")},
            },
        ),
    ]
