# Generated by Django 5.2.8 on 2025-11-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_sharecount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Brief summary of the article", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="SEO meta description", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, help_text="Schedule publish date/time", null=True
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of title",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("password", "Password Protected"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
