# Generated by Django 5.2.8 on 2025-11-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_news_options_news_excerpt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL-friendly version of title", max_length=255
            ),
        ),
    ]
