# Generated by Django 5.2.8 on 2025-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_alter_news_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether subscriber is active"
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
