# Generated by Django 5.2.8 on 2025-12-07 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("editorial", "Editorial"),
                            ("technology", "Technology"),
                            ("business", "Business"),
                            ("design", "Design"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "responsibilities",
                    models.TextField(help_text="Enter one responsibility per line"),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Enter one requirement per line"),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        help_text="Upload resume in PDF, DOC, or DOCX format (Max 5MB)",
                        upload_to="resumes/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("interview", "Interview Scheduled"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                (
                    "job_opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="news.jobopening",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_date"],
            },
        ),
    ]
