# Generated by Django 5.2.8 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_jobopening_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for the advertisement", max_length=200
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("sidebar", "Sidebar"),
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("inline", "Inline Content"),
                        ],
                        default="sidebar",
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("300x250", "Medium Rectangle (300x250)"),
                            ("728x90", "Leaderboard (728x90)"),
                            ("160x600", "Wide Skyscraper (160x600)"),
                            ("300x600", "Half Page (300x600)"),
                            ("320x50", "Mobile Banner (320x50)"),
                            ("custom", "Custom Size"),
                        ],
                        default="300x250",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Advertisement image", upload_to="advertisements/"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(help_text="Target URL when ad is clicked"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Alternative text for accessibility", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this ad currently active?"
                    ),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times ad was clicked"
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times ad was viewed"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When to start showing this ad"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing this ad (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
