# Generated by Django 5.2.8 on 2025-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_advertisement"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_service", "Terms of Service"),
                            ("cookie_policy", "Cookie Policy"),
                            ("ethics_policy", "Ethics Policy"),
                            ("editorial_guidelines", "Editorial Guidelines"),
                            ("about", "About Us"),
                        ],
                        help_text="Type of legal/administrative page",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "content_json",
                    models.JSONField(
                        help_text="JSON structure containing the page content"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
                "ordering": ["-last_updated"],
            },
        ),
    ]
