# Generated by Django 5.2.8 on 2025-12-08 14:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_legalpage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGenerationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("breaking_news", "Breaking News"),
                            ("analysis", "Analysis & Opinion"),
                            ("investigative", "Investigative Report"),
                            ("feature", "Feature Story"),
                            ("data_driven", "Data-Driven Report"),
                            ("explainer", "Explainer"),
                            ("listicle", "Listicle"),
                        ],
                        default="analysis",
                        max_length=50,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("google", "Google (Gemini)"),
                        ],
                        default="openai",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4-turbo-preview",
                        help_text="Model name (e.g., gpt-4, claude-3-opus)",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System prompt defining AI behavior and mission (AI Analitica standards)"
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User prompt template with placeholders: {keyword}, {word_count}, etc."
                    ),
                ),
                ("outline_prompt", models.TextField(blank=True)),
                ("research_prompt", models.TextField(blank=True)),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.7"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4000,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(128000),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "presence_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "target_word_count",
                    models.IntegerField(
                        default=1500,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "num_headings",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                ("include_statistics", models.BooleanField(default=True)),
                ("include_quotes", models.BooleanField(default=True)),
                ("include_internal_links", models.BooleanField(default=True)),
                (
                    "max_ai_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Maximum acceptable AI detection score",
                        max_digits=5,
                    ),
                ),
                (
                    "max_plagiarism_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Maximum acceptable plagiarism percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "min_seo_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        help_text="Minimum acceptable SEO score",
                        max_digits=5,
                    ),
                ),
                (
                    "min_readability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        help_text="Minimum acceptable readability score",
                        max_digits=5,
                    ),
                ),
                (
                    "max_bias_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Maximum acceptable bias score (AI Analitica: <20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "auto_humanize",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically humanize AI-generated content",
                    ),
                ),
                (
                    "auto_rewrite_plagiarism",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically rewrite plagiarized sections",
                    ),
                ),
                (
                    "auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically publish if all quality checks pass",
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Config",
                "verbose_name_plural": "AI Generation Configs",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="KeywordSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("google_trends", "Google Trends"),
                            ("news_api", "News API"),
                            ("twitter_trends", "Twitter Trends"),
                            ("internal", "Internal Analytics"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "search_volume",
                    models.IntegerField(
                        blank=True,
                        help_text="Monthly search volume",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "competition",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "viability_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI-calculated viability score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=3,
                        help_text="Priority level (1=highest, 5=lowest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business", "Business"),
                            ("political", "Political"),
                            ("tech", "Tech"),
                            ("education", "Education"),
                        ],
                        default="business",
                        max_length=50,
                    ),
                ),
                (
                    "suggested_angles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-suggested article angles",
                    ),
                ),
                (
                    "related_keywords",
                    models.JSONField(
                        blank=True, default=list, help_text="Related keywords for SEO"
                    ),
                ),
                (
                    "suggested_template",
                    models.CharField(
                        blank=True,
                        help_text="Recommended article template",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword Source",
                "verbose_name_plural": "Keyword Sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("breaking_news", "Breaking News"),
                            ("analysis", "Analysis & Opinion"),
                            ("investigative", "Investigative Report"),
                            ("feature", "Feature Story"),
                            ("data_driven", "Data-Driven Report"),
                            ("explainer", "Explainer"),
                            ("listicle", "Listicle"),
                        ],
                        default="analysis",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("reviewing", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_stage",
                    models.CharField(
                        choices=[
                            ("keyword_analysis", "Keyword Analysis"),
                            ("research", "Research & Data Collection"),
                            ("outline", "Outline Generation"),
                            ("content_generation", "Content Generation"),
                            ("humanization", "Humanization"),
                            ("ai_detection", "AI Detection Check"),
                            ("plagiarism_check", "Plagiarism Check"),
                            ("bias_detection", "Bias Detection"),
                            ("fact_verification", "Fact Verification"),
                            ("perspective_analysis", "Perspective Analysis"),
                            ("seo_optimization", "SEO Optimization"),
                            ("meta_generation", "Meta Tags Generation"),
                            ("image_generation", "Image Generation"),
                            ("quality_check", "Final Quality Check"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="keyword_analysis",
                        max_length=50,
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        default="gpt-4-turbo-preview",
                        help_text="AI model used for generation",
                        max_length=100,
                    ),
                ),
                (
                    "content_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured content with sections, headings, etc.",
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(blank=True, help_text="Raw markdown/HTML content"),
                ),
                (
                    "research_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Research sources and data collected",
                    ),
                ),
                (
                    "outline",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Article outline and structure",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("focus_keywords", models.JSONField(blank=True, default=list)),
                ("og_title", models.CharField(blank=True, max_length=60)),
                ("og_description", models.CharField(blank=True, max_length=160)),
                (
                    "target_word_count",
                    models.IntegerField(
                        default=1500,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                ("actual_word_count", models.IntegerField(default=0)),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI detection score (lower is better, <50 target)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "plagiarism_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plagiarism percentage (lower is better, <5% target)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "seo_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="SEO score (higher is better, >75 target)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "readability_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Readability score (60-80 target)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "bias_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bias detection score (lower is better, <20% target - AI Analitica standard)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fact_check_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fact verification score (higher is better, 100% citations required)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "overall_quality_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weighted overall quality score",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="DALL-E generated image URL"),
                ),
                ("image_local_path", models.CharField(blank=True, max_length=500)),
                ("image_prompt", models.TextField(blank=True)),
                ("image_alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "references",
                    models.JSONField(
                        blank=True, default=list, help_text="List of source references"
                    ),
                ),
                ("internal_links", models.JSONField(blank=True, default=list)),
                ("external_links", models.JSONField(blank=True, default=list)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("failed_stage", models.CharField(blank=True, max_length=50)),
                (
                    "generation_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Total generation time in seconds",
                        null=True,
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Estimated API cost in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token usage breakdown by stage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "published_article",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_source",
                        to="news.news",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ai_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.keywordsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Article",
                "verbose_name_plural": "AI Articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIWorkflowLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("keyword_analysis", "Keyword Analysis"),
                            ("research", "Research & Data Collection"),
                            ("outline", "Outline Generation"),
                            ("content_generation", "Content Generation"),
                            ("humanization", "Humanization"),
                            ("ai_detection", "AI Detection Check"),
                            ("plagiarism_check", "Plagiarism Check"),
                            ("bias_detection", "Bias Detection"),
                            ("fact_verification", "Fact Verification"),
                            ("perspective_analysis", "Perspective Analysis"),
                            ("seo_optimization", "SEO Optimization"),
                            ("meta_generation", "Meta Tags Generation"),
                            ("image_generation", "Image Generation"),
                            ("quality_check", "Final Quality Check"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Input data for this stage"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Output/result from this stage",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "execution_time",
                    models.IntegerField(
                        default=0, help_text="Execution time in milliseconds"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=10
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=100)),
                ("retry_number", models.IntegerField(default=0)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual Retry")],
                        default="auto",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_logs",
                        to="news.aiarticle",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Workflow Log",
                "verbose_name_plural": "AI Workflow Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["article", "stage"],
                        name="news_aiwork_article_f5c2d8_idx",
                    ),
                    models.Index(
                        fields=["status", "-timestamp"],
                        name="news_aiwork_status_1852e7_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="keywordsource",
            index=models.Index(
                fields=["status", "-created_at"], name="news_keywor_status_09b308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keywordsource",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="news_keywor_priorit_7d84b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="keywordsource",
            index=models.Index(
                fields=["category", "status"], name="news_keywor_categor_1a378f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiarticle",
            index=models.Index(
                fields=["status", "-created_at"], name="news_aiarti_status_c61147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiarticle",
            index=models.Index(
                fields=["workflow_stage", "status"],
                name="news_aiarti_workflo_70e0a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiarticle",
            index=models.Index(
                fields=["keyword", "status"], name="news_aiarti_keyword_d871c2_idx"
            ),
        ),
    ]
