# Generated by Django 5.2.8 on 2025-12-08 17:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0015_aigenerationconfig_keywordsource_aiarticle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSourceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Configuration name", max_length=255),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="List of keywords/topics to search for"
                    ),
                ),
                (
                    "source_websites",
                    models.JSONField(
                        default=list,
                        help_text="List of news website URLs to scrape from",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Politics", "Politics"),
                            ("Business", "Business"),
                            ("Technology", "Technology"),
                            ("Health", "Health"),
                            ("Education", "Education"),
                            ("Entertainment", "Entertainment"),
                            ("Sports", "Sports"),
                            ("Science", "Science"),
                            ("Environment", "Environment"),
                            ("Culture", "Culture"),
                        ],
                        default="Politics",
                        max_length=50,
                    ),
                ),
                (
                    "max_articles_per_scrape",
                    models.IntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "scrape_frequency_hours",
                    models.IntegerField(
                        default=24, help_text="How often to scrape (in hours)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_source_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News Source Configuration",
                "verbose_name_plural": "News Source Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(help_text="Scraped article content")),
                ("summary", models.TextField(blank=True)),
                ("source_url", models.URLField(max_length=1000)),
                ("source_website", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "matched_keywords",
                    models.JSONField(
                        default=list, help_text="Keywords that matched this article"
                    ),
                ),
                (
                    "image_urls",
                    models.JSONField(
                        default=list, help_text="Image URLs found in article"
                    ),
                ),
                (
                    "reference_urls",
                    models.JSONField(
                        default=list, help_text="Reference/citation URLs from article"
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved for Generation"),
                            ("rejected", "Rejected"),
                            ("generated", "Article Generated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_scraped_article",
                        to="news.aiarticle",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_scraped_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_articles",
                        to="news.newssourceconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraped Article",
                "verbose_name_plural": "Scraped Articles",
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-scraped_at"],
                        name="news_scrape_status_08c8af_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="news_scrape_categor_4a4b08_idx",
                    ),
                    models.Index(
                        fields=["source_config", "-scraped_at"],
                        name="news_scrape_source__685285_idx",
                    ),
                ],
            },
        ),
    ]
