# Generated by Django 5.2.8 on 2025-12-08 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_newssourceconfig_scrapedarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiarticle",
            name="ai_model_used",
            field=models.CharField(
                default="gemini-2.0-flash-exp",
                help_text="AI model used for generation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationconfig",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("google", "Google (Gemini)"),
                ],
                default="google",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationconfig",
            name="max_tokens",
            field=models.IntegerField(
                default=8000,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(128000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationconfig",
            name="model_name",
            field=models.CharField(
                default="gemini-2.0-flash-exp",
                help_text="Model name (e.g., gemini-2.0-flash-exp, gpt-4, claude-3-opus)",
                max_length=100,
            ),
        ),
    ]
