# Generated by Django 5.2.8 on 2025-12-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_update_to_gemini"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigenerationconfig",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("google", "Google (Gemini)"),
                    ("groq", "Groq (Ultra-Fast)"),
                ],
                default="google",
                max_length=50,
            ),
        ),
    ]
