# Generated by Django 5.2.8 on 2025-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_add_groq_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationconfig",
            name="stage_configs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-stage AI provider and model configuration. Format: {'outline': {'provider': 'groq', 'model': 'llama-3.1-8b-instant'}, ...}",
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationconfig",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("google", "Google (Gemini)"),
                    ("groq", "Groq (Ultra-Fast)"),
                    ("naturalwrite", "NaturalWrite (Humanizer)"),
                ],
                default="google",
                max_length=50,
            ),
        ),
    ]
